# Generated by Django 4.0.5 on 2022-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_client_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='anon_channel_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
