# Generated by Django 4.0.5 on 2022-08-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_clients_anon_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='anon_channel_name',
        ),
        migrations.AddField(
            model_name='clients',
            name='group_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
