# Generated by Django 4.0.5 on 2022-10-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_channel_group_delete_clients_channel_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
