# Generated by Django 4.0.5 on 2022-10-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_group_name_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='group_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
