# Generated by Django 4.0.5 on 2022-10-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_channel_unique_id_alter_channel_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='unique_id',
            new_name='user_id',
        ),
        migrations.CreateModel(
            name='MessageLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user_id', models.IntegerField()),
                ('time_created', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
            ],
        ),
    ]
